### ISSUE TITLE
Use Array Literals

### ISSUE THREAD

**Issue by aric87** [bpinali/fretboard-scale-generator#3]
https://github.com/bpinali/fretboard-scale-generator/blob/master/scripts/main.js#L41

If you use Array(), it should be `new Array()`. However, you should be using array literals instead. `scales = [];` It's more in line with best practices, and it's faster. Same goes for all the Array() functions you're using through this section. They  should be `scales['major'] = [0, 2, 4, 5, 7, 9, 11];`

**Comment by bpinali** [comment]
Fixed.
