### ISSUE TITLE
streamline where you can

### ISSUE THREAD

**Issue by aric87** [bpinali/fretboard-scale-generator#8]
Creating a variable inside a function requires the parser to look through the function, define the variable in memory, set it to undefined, the run your code, then determine if the variable is needed after the function runs, and garbage collect (remove from memory) if it's not. In this case, and likely others, you can streamline by removing the variable. 
https://github.com/bpinali/fretboard-scale-generator/blob/master/scripts/main.js#L136

Do it this way to avoid creating the variable, then removing from memory; 

```
function getTuning() {
    // harvest the user selected predefined tuning value
     return $("#tuningSelect").val();
}
```

**Comment by bpinali** [comment]
Fixed in prior commit: https://github.com/bpinali/fretboard-scale-generator/commit/729ffc8f99836763f5b1b398d4cf99c91259b155
